Updated configure script to fetch SUSAN

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4248,11 +4248,24 @@ else
 	{ echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6; }
 	{ echo "$as_me:$LINENO: WARNING: susan2l.c not found. I can not distribute it, but it can be found here:
-http://users.fmrib.ox.ac.uk/~steve/susan/susan2l.c
-" >&5
+http://users.fmrib.ox.ac.uk/~steve/susan/susan2l.c" >&5
 echo "$as_me: WARNING: susan2l.c not found. I can not distribute it, but it can be found here:
-http://users.fmrib.ox.ac.uk/~steve/susan/susan2l.c
-" >&2;}
+http://users.fmrib.ox.ac.uk/~steve/susan/susan2l.c" >&2;}
+
+	{ echo "$as_me:$LINENO: Attempting to fetch..." >&5
+echo "$as_me: Attempting to fetch..." >&6;}
+
+	if wget http://users.fmrib.ox.ac.uk/~steve/susan/susan2l.c
+	then
+		{ echo "$as_me:$LINENO: Fetch successful." >&5
+echo "$as_me: Fetch successful." >&6;}
+		susan="mod_susan.o susan.o"
+
+		CXXFLAGS="$CXXFLAGS -DUSESUSAN"
+	else
+		{ echo "$as_me:$LINENO: WARNING: Unable to fetch susan2l.c. Disabling." >&5
+echo "$as_me: WARNING: Unable to fetch susan2l.c. Disabling." >&2;}
+	fi
 fi
 
 ################################################################################
@@ -4747,7 +4760,6 @@ then
 	echo JIT compilation is not enabled: the program will run very slowly.
 	echo You need a working 32 bit x86 executable to enable JIT.
 	echo
-	CXXFLAGS="$CXXFLAGS -DNOJIT"
 else
 	CXXFLAGS="$CXXFLAGS -DJIT"
 fi
