-ansi -pedantic -Wall -Wextra clean compile

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2353,13 +2353,325 @@ ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ex
 ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
 
 
+################################################################################
+#
+# Useful macros
+#
+
+
+
+
+
+
+
+
+
+	if test "" == ""
+	then
+		{ echo "$as_me:$LINENO: checking if compiler flag -Wall works" >&5
+echo $ECHO_N "checking if compiler flag -Wall works... $ECHO_C" >&6; }
+	else
+		{ echo "$as_me:$LINENO: checking " >&5
+echo $ECHO_N "checking ... $ECHO_C" >&6; }
+	fi
+	save_CXXFLAGS="$CXXFLAGS"
+	CXXFLAGS="$CXXFLAGS -Wall"
+
+
+
+
+cat >conftest.$ac_ext <<_ACEOF
+int main(){}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_cxx_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  cvd_conf_test=1
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	cvd_conf_test=0
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+
+
+
+
+
+	if test $cvd_conf_test = 1
+	then
+		{ echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+		ts_success=yes
+	else
+		{ echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+		CXXFLAGS="$save_CXXFLAGS"
+		ts_success=no
+	fi
+
+
+	if test "" == ""
+	then
+		{ echo "$as_me:$LINENO: checking if compiler flag -Wextra works" >&5
+echo $ECHO_N "checking if compiler flag -Wextra works... $ECHO_C" >&6; }
+	else
+		{ echo "$as_me:$LINENO: checking " >&5
+echo $ECHO_N "checking ... $ECHO_C" >&6; }
+	fi
+	save_CXXFLAGS="$CXXFLAGS"
+	CXXFLAGS="$CXXFLAGS -Wextra"
+
+
+
+	cat >conftest.$ac_ext <<_ACEOF
+int main(){}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_cxx_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  cvd_conf_test=1
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	cvd_conf_test=0
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+
+
+
+
+
+	if test $cvd_conf_test = 1
+	then
+		{ echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+		ts_success=yes
+	else
+		{ echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+		CXXFLAGS="$save_CXXFLAGS"
+		ts_success=no
+	fi
+
+
+	if test "" == ""
+	then
+		{ echo "$as_me:$LINENO: checking if compiler flag -W works" >&5
+echo $ECHO_N "checking if compiler flag -W works... $ECHO_C" >&6; }
+	else
+		{ echo "$as_me:$LINENO: checking " >&5
+echo $ECHO_N "checking ... $ECHO_C" >&6; }
+	fi
+	save_CXXFLAGS="$CXXFLAGS"
+	CXXFLAGS="$CXXFLAGS -W"
+
+
+
+	cat >conftest.$ac_ext <<_ACEOF
+int main(){}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_cxx_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  cvd_conf_test=1
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	cvd_conf_test=0
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+
+
+
+
+
+	if test $cvd_conf_test = 1
+	then
+		{ echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+		ts_success=yes
+	else
+		{ echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+		CXXFLAGS="$save_CXXFLAGS"
+		ts_success=no
+	fi
+
+
+	if test "" == ""
+	then
+		{ echo "$as_me:$LINENO: checking if compiler flag -ansi works" >&5
+echo $ECHO_N "checking if compiler flag -ansi works... $ECHO_C" >&6; }
+	else
+		{ echo "$as_me:$LINENO: checking " >&5
+echo $ECHO_N "checking ... $ECHO_C" >&6; }
+	fi
+	save_CXXFLAGS="$CXXFLAGS"
+	CXXFLAGS="$CXXFLAGS -ansi"
+
+
+
+	cat >conftest.$ac_ext <<_ACEOF
+int main(){}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_cxx_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  cvd_conf_test=1
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	cvd_conf_test=0
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+
+
+
+
+
+	if test $cvd_conf_test = 1
+	then
+		{ echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+		ts_success=yes
+	else
+		{ echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+		CXXFLAGS="$save_CXXFLAGS"
+		ts_success=no
+	fi
+
+
+	if test "" == ""
+	then
+		{ echo "$as_me:$LINENO: checking if compiler flag -pedantic works" >&5
+echo $ECHO_N "checking if compiler flag -pedantic works... $ECHO_C" >&6; }
+	else
+		{ echo "$as_me:$LINENO: checking " >&5
+echo $ECHO_N "checking ... $ECHO_C" >&6; }
+	fi
+	save_CXXFLAGS="$CXXFLAGS"
+	CXXFLAGS="$CXXFLAGS -pedantic"
+
+
+
+	cat >conftest.$ac_ext <<_ACEOF
+int main(){}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_cxx_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  cvd_conf_test=1
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	cvd_conf_test=0
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+
+
+
+
+
+	if test $cvd_conf_test = 1
+	then
+		{ echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+		ts_success=yes
+	else
+		{ echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+		CXXFLAGS="$save_CXXFLAGS"
+		ts_success=no
+	fi
+
 
 ################################################################################
 #
 # Check for libcvd
 #
 cvd=yes
-
 ac_ext=cpp
 ac_cpp='$CXXCPP $CPPFLAGS'
 ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
